apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: critical-app
  labels:
    app: critical-app
    role: redis
spec:
  ports:
    - port: 6379
  selector:
    app: critical-app
    role: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: critical-app
spec:
  template:
    metadata:
      labels:
        app: critical-app
        role: redis
    spec:
      containers:
        - name: redis
          image: redis:2.8.19
